
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'prism_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'prism_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

models:
  prism_dbt:
  
    +schema: "{{ target.schema }}"
    mlv:
      raw:
        +schema: raw
        +materialized: view
      staging:
        +schema: staging
        +materialized: table
      sandbox:
        +schema: sandbox
        +materialized: view
      marts:
        +schema: marts
        +materialized: table
      acn:
        +schema: acn
        +materialized: table
      blhc:
        +schema: blhc
        +materialized: table
      # prod:
      #   +schema: prod
      #   +materialized: table


seeds:
  prism_dbt: # Replace with the name in your dbt_project.yml
    acn:
      masked_acn_consolidated_raw_data_fy2324_fy4525:
        +schema: dev_acn
        +column_types:
          corpcode: text
          branchdesc: text
          claimno: text
          admissiondate: date
          gender: text
          membershiptype: text
          mainspecialization: text
          loatype: text
          icdcode: text
          approved: numeric
          age: numeric
          benefitid: text
          ruvcode: text
          cptdesc: text
          physicianname: text
          physiciancode: text
          maskedcardno: text

      seed_blhc_labs_raw:
        +schema: seed_blhc
        +column_types:
          reference_number: text
          final_patient_code: text
          result_date: text
          list_of_tests: text
          hba1c_ngsp: text
          glucose_fastingfbs_mgdl: text
          creatinine_mgdl: text
          ldl_cholesterol_mgdl: text
          record_url: text
          earliest_hba1c: text
          latest_hba1c: text
          within_hba1c_cutoff: text
          earliest_lipid_profile: text
          latest_lipid_profile: text
          within_lipid_profile_cutoff: text
          earliest_fbs: text
          latest_fbs: text
          within_fbs_cutoff: text
          
      seed_blhc_bp_raw:
        +schema: seed_blhc
        +column_types:
          reference_number: text
          final_patient_code: text
          maxicare_card_number: text
          result_date: text
          systolic_blood_pressure: text
          diastolic_blood_pressure: text
          source: text
          earliest_sbp: text
          latest_sbp: text
          within_sbp_cutoff: text
          earliest_dbp: text
          latest_dbp: text
          within_dbp_cutoff: text

      seed_reference_member_base:
        +schema: seed_blhc
        +column_types:
          Patient Code-Full Name: text
          Final Patient Code: text
          Card Number Final: text
          Processing Date - Final: date 
          Baseline Test Date - Final: date
          Dropout Date: date


    pcc_data:
      seed_pcc_availments_raw_data:
        +schema: seed_pcc
        +column_types:
          card_number: text
          transaction_id: text
          availment_type: text
          icd_code: text
          icd_description: text
          pcc_branch_name: text
          physiciancode: text
          physicianname: text
          service_price: text
          availment_date: date
      seed_pcc_availments_shortlisted_card_numbers:
        +schema: seed_pcc
        +column_types:
          maskedcardno: text
          maxicare_cardno: text
          cardno_trimmed: text
          total_availment_cost: text
          total_availment_count: text
          earliest_availment_date: date
          latest_availment_date: date
      seed_pcc_physician_codes:
        +schema: seed_pcc
        +column_types:
          physiciancode: text
          physicianname: text
          specialization: text
          sub_specialization: text
          is_coordinator: boolean
          practices_in_pcc: boolean
      seed_per_pcc_branch_specialization:
        +schema: seed_pcc
        +column_types:
          branch: text
          specialization: text
          count: integer
      seed_per_pcc_branch_specialization_summary:
        +schema: seed_pcc
        +column_types:
          branch: text
          specialization: integer
          total_physicians: integer

    sandbox: 
      +schema: seed_sandbox
      physiciancode_with_bills:
        +column_types:
          physiciancode: varchar(255) 
      source_claims_with_bills:
        +column_types:
          claimno: varchar(255)
      bl_unmaskedcardno:
        +column_types:
          maskedcardno: varchar(255)
          cardno: varchar(255)
          blp_cardno: varchar(255)
      blp_icdcodes_v2:
        +column_type:
          icdcode: varchar(255)
          description: text
          final_tagging: text
      crf_cptcodes:
        +column_type:
          status_group: varchar(255)
          subcategory: varchar(255)
          cptcode: varchar(255)
          description: text
      physiciannames:
        +column_types:
          physicianname: varchar(255)
          physiciancode: varchar(255)
      t500_md:
        +column_types:

          physiciancode: text
          providercode: text
          physicianname: text
          specialization: text
          total_unique_patient_cnt: numeric
          total_claim_count: numeric
          all_claims_sum_of_util: numeric
          ave_12_month_util_per_patient: numeric
          
          # OPL (Outpatient) Metrics
          opl_unique_px_cnt_at_least_one: numeric
          opl_unique_px_count_at_least_one_pct: numeric
          opl_ave_claims_per_px_at_least_one: numeric
          opl_total_claims: numeric
          opl_ave_cost_per_claim_per_px_at_least_one: numeric
          opl_sum_of_util: numeric
          opl_ave_twelve_month_util_per_px: numeric
          
          # INP (Inpatient) Metrics
          inp_unique_px_count_at_least_one: numeric
          inp_unique_px_count_at_least_one_pct: numeric
          inp_ave_claims_per_px_at_least_one: numeric
          inp_total_claims: numeric
          inp_ave_cost_per_claim_per_px_at_least_one: numeric
          inp_sum_of_util: numeric
          inp_ave_twelve_month_util_per_px: numeric
          
          # Others Metrics
          others_unique_px_count_at_least_one: numeric
          others_unique_px_count_at_least_one_pct: numeric
          others_ave_claims_per_px_at_least_one: numeric
          others_total_claims: numeric
          others_ave_cost_per_claim_per_px_at_least_one: numeric
          others_sum_of_util: numeric
          others_ave_twelve_month_util_per_px: numeric
          
          # Philhealth Metrics
          total_philhealth: numeric
          ave_philhealth_claim: numeric
    ocr:
      +schema: seed_ocr
      ocr_012126:
        +column_types:
          item_name: text
          item_name_simple_clean: text
          item_name_hard_clean: text
          item_quantity: numeric
          item_unit_gross_price: numeric
          total_price: numeric
          loe_folder: text
          source_file: text
          file_name: text
          claimno: varchar(255)
          physiciancode: varchar(255)
          icdcode: varchar(255)