version: 2

models:
  - name: physiciannames
    columns:
      - name: physicianname
        tests:
          - unique
      - name: physiciancode
        tests:
          - unique
  - name: mlv
    description: "Tests for the combined table"
    columns:
      - name: maskedcardno
        tests:
          - not_null
      - name: starting_claimno
        tests:
          - not_null
      - name: starting_admissiondate
        tests:
          - not_null
      - name: starting_dischargedate
        tests:
          - not_null
      - name: starting_physiciancode
        tests:
          - not_null
      - name: starting_primaryicdgroup
        tests:
          - not_null
      - name: starting_primaryicdcode
        tests:
          - not_null
          - relationships:
              to: ref('blp_icdcodes_v2')
              field: icdcode
      - name: starting_providername
        tests:
          - not_null
      - name: starting_loatype
        tests:
          - not_null
          - accepted_values:
              values: ['OP_CONSULT','OP LAB']
      - name: starting_bill
        tests:
          - not_null
      - name: starting_approved
        tests:
          - not_null
      - name: starting_philhealth
        tests:
          - not_null
      - name: claim_sequence
        tests:
          - not_null
      - name: subsequent_claimno
        tests:
          - not_null
          - unique
      - name: subsequent_admissiondate
        tests:
          - not_null
      - name: subsequent_dischargedate
        tests:
          - not_null
      - name: subsequent_primary_physiciancode_by_rank
        tests:
          - not_null
      - name: subsequent_primary_physiciancode_by_approved_amount
        tests:
          - not_null
      - name: subsequent_primaryicdgroup
        tests:
          - not_null
      - name: subsequent_primaryicdcode
        tests:
          - not_null
      - name: subsequent_primaryicddesc
        tests:
          - not_null
      - name: subsequent_providername
        tests:
          - not_null
      - name: subsequent_loatype
        tests:
          - not_null
      - name: subsequent_coverage
        tests:
          - not_null
      - name: subsequent_bill
        tests:
          - not_null
      - name: subsequent_approved
        tests:
          - not_null
      - name: subsequent_philhealth
        tests:
          - not_null
  - name: ocr_cleaned_012126   # replace with your model name
    description: "Combined OCR line items with cleaned claimno and physiciancode"
    columns:
      - name: item_name
        tests:
          - not_null
      - name: item_name_simple_clean
        tests:
          - not_null
      - name: item_name_hard_clean
        tests:
          - not_null
      - name: item_quantity
        tests:
          - not_null
      - name: item_unit_gross_price
        tests:
          - not_null
      - name: total_price
        tests:
          - not_null
      - name: file_claimno
        tests:
          - not_null
      - name: subsequent_claimno
        tests:
          - not_null
      - name: maskedcardno
        tests:
          - not_null
      - name: starting_physician_providername
        tests:
          - not_null
      - name: subsequent_physician_providername
        tests:
          - not_null
      - name: subsequent_physiciancode
        tests:
          - not_null
      - name: subsequent_providername
        tests:
          - not_null
      - name: icdcode
        tests:
          - not_null
