version: 2

sources:
  - name: acn_raw_data
    schema: dev_acn
    tables:
      - name: masked_acn_raw_2425

  - name: md_fuzzy_from_physicianinfo
    schema: dev_acn   # CHANGE THIS if Step 1 shows different schema
    tables:
      - name: physician_name_matching_results

  - name: masked_acn_consolidated_raw_data
    schema: dev_acn   # CHANGE THIS if Step 1 shows different schema
    tables:
      - name: masked_acn_consolidated_raw_data_fy2324_fy2425
      - name: updated_masked_acn_consolidated_raw_data_fy2324_fy2425

  - name: public_data
    database: prism_db
    schema: public
    tables:
      - name: raw_claims_2023_2025

  - name: mxc_raw_claims
    database: prism_db
    schema: mxc_raw_claims
    tables:
      - name: prism_2019_jan_to_jun
      - name: prism_2019_july_to_dec
      - name: prism_2020_jan_to_jun
      - name: prism_2020_july_to_dec
      - name: prism_2021_jan_to_jun
      - name: prism_2021_july_to_dec
      - name: prism_2022_jan_to_jun
      - name: prism_2022_july_to_dec
      - name: prism_2023_jan_to_jun
      - name: prism_2023_july_to_dec
      - name: prism_2024_jan_to_jun
      - name: prism_2024_july_to_dec
      - name: prism_2025_jan_to_mar
      - name: acn_claims_2019
      - name: acn_claims_2020
      - name: acn_claims_2021
      - name: acn_claims_2022
      - name: acn_claims_2023
      - name: acn_claims_2024
      - name: acn_claims_2025
